# Generated by Django 5.2 on 2025-04-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HiredEmployees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('datetime', models.TextField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.departments')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.jobs')),
            ],
        ),
    ]
